services:
  v:
    image: thevlang/vlang:alpine
    tty: true
    entrypoint: v
    working_dir: /home/v
    volumes:
      - .:/home/v
    ports:
      - 80:80

  siege:
    image: jstarcher/siege:latest
    entrypoint: siege
    # DCU then docker compose run --service-ports siege --time=30s --concurrent=50 --internet --no-parser v
