services:
  v:
    build: ./docker/v
    tty: true
    entrypoint: v
    working_dir: /home/v
    volumes:
      - .:/home/v
    ports:
      - 80:80

  npm:
    image: node:23-alpine
    entrypoint: npm
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - 5173:5173

  siege:
    image: jstarcher/siege:latest
    entrypoint: siege
    # DCU then docker compose run --service-ports siege --time=30s --concurrent=50 --internet --no-parser v
