on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests-latest:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Tests
        run: docker compose run --rm v test .
  tests_0_4_9:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Tests
        run: docker compose run --rm v049 test .
  tests_0_4_8:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Tests
        run: docker compose run --rm v048 test .
